services:
  server:
    container_name: webapp
    build:
      context: .
      args:
      - DEBUG=${DEBUG}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - FLASK_APP=${FLASK_APP}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK=${GOOGLE_CALLBACK}
      - ADMIN_USERS=${ADMIN_USERS}
    ports:
      - 5111:5000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    user: "${UID}:${GID}"
    # to persist the server connection data need to share the Docker volume with the pgadmin container
    # https://stackoverflow.com/questions/61087782/pgadmin-4-save-server-connection-details
    volumes:
      - db-data:/var/lib/pgadmin
      - pgadmin-sessions:/var/lib/pgadmin/sessions
volumes:
  db-data:
  pgadmin-sessions:
# secrets:
#   db-password:
#     file: db/password.txt

