"""origin file column

Revision ID: 2524def5b2d5
Revises: c2153ae5e83a
Create Date: 2024-11-26 06:58:21.833970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2524def5b2d5'
down_revision = 'c2153ae5e83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_file', sa.VARCHAR(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('origin_file')

    # ### end Alembic commands ###
