"""nullable genesis_location_id

Revision ID: 3770ddb7555f
Revises: 14b266d2e362
Create Date: 2024-11-24 17:35:32.509144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3770ddb7555f'
down_revision = '14b266d2e362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('genesis_location_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('genesis_location_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
