"""update decision_destinations

Revision ID: 8d260f51f8f1
Revises: 2524def5b2d5
Create Date: 2024-12-08 19:47:36.004281

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d260f51f8f1"
down_revision = "2524def5b2d5"
branch_labels = None
depends_on = None


# WARNING: This updates the pk of the decision_destinations table to include the id column
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decision_destinations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(
            "destionation_location_position_unique", type_="unique"
        )
        batch_op.create_unique_constraint(
            "destination_location_position_unique",
            ["decision_id", "destination_location_id", "position"],
        )
        # Drop the old primary key constraint
        batch_op.drop_constraint("decision_destinations_pkey", type_="primary")

        # Create the new primary key constraint
        batch_op.create_primary_key(
            "decision_destinations_pkey",
            ["id", "decision_id", "destination_location_id"],
        )

    # ### end Alembic commands ###


# Downgrade to the old primary key that is just decision_id and destination_location_id
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decision_destinations", schema=None) as batch_op:
        # Drop the new primary key constraint
        batch_op.drop_constraint("decision_destinations_pkey", type_="primary")
        batch_op.drop_constraint("destination_location_position_unique", type_="unique")
        batch_op.create_unique_constraint(
            "destionation_location_position_unique",
            ["destination_location_id", "position"],
        )
        batch_op.drop_column("id")

        # Recreate the old primary key constraint
        batch_op.create_primary_key(
            "decision_destinations_pkey",
            ["decision_id", "destination_location_id"],
        )

    # ### end Alembic commands ###
