"""Create decision and decision_destinations tables with foreign keys

Revision ID: a62df723c8ad
Revises: be6309d09945
Create Date: 2024-11-13 07:12:00.486507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62df723c8ad'
down_revision = 'be6309d09945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_destinations',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', 'destination_location_id'),
    sa.UniqueConstraint('destination_location_id', 'position', name='destionation_location_position_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_destinations')
    op.drop_table('decisions')
    # ### end Alembic commands ###
