"""default and version columns

Revision ID: ad3089637c86
Revises: a62df723c8ad
Create Date: 2024-11-23 23:28:14.809532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3089637c86'
down_revision = 'a62df723c8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', autoincrement=True, nullable=False))
        batch_op.create_index('ix_season_default_unique', ['default'], unique=True, postgresql_where=sa.text('"default" = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index('ix_season_default_unique', postgresql_where=sa.text('"default" = true'))
        batch_op.drop_column('version')
        batch_op.drop_column('default')

    # ### end Alembic commands ###
