"""create seasons and locations tables

Revision ID: be6309d09945
Revises: 744ed41773af
Create Date: 2024-11-07 07:01:51.095125

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be6309d09945"
down_revision = "744ed41773af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=2048), nullable=False),
        sa.Column("genesis_location_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genesis_location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seasons")
    op.drop_table("locations")
    # ### end Alembic commands ###
