"""drop version column

Revision ID: c2153ae5e83a
Revises: f3439287e7b9
Create Date: 2024-11-26 06:48:24.360224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2153ae5e83a'
down_revision = 'f3439287e7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
