"""locations season_id

Revision ID: e45a0feee25c
Revises: 3770ddb7555f
Create Date: 2024-11-24 17:54:24.259295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45a0feee25c'
down_revision = '3770ddb7555f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key('fk_locations_season_id', 'seasons', ['season_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_locations_season_id', type_='foreignkey')
        batch_op.drop_column('season_id')

    # ### end Alembic commands ###
