"""Add locations_decisions associations

Revision ID: f9ef205c7950
Revises: be6309d09945
Create Date: 2024-11-09 19:02:16.929586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef205c7950'
down_revision = 'be6309d09945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations_decisions',
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_location_id', 'destination_location_id', 'decision_id'),
    sa.UniqueConstraint('source_location_id', 'position', name='source_position_unique')
    )
    with op.batch_alter_table('locations_decisions', schema=None) as batch_op:
        batch_op.create_index('locations_decisions_position_idx', ['source_location_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations_decisions', schema=None) as batch_op:
        batch_op.drop_index('locations_decisions_position_idx')

    op.drop_table('locations_decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
